kind: pipeline
type: exec
name: homesite

steps:
  - name: build
    image: node:20-slim
    commands:
      - npm config set registry http://mirrors.cloud.tencent.com/npm/
      - corepack enable
      - corepack use pnpm
      - pnpm i
  - name: build-app
    image: node:20-slim
    commands:
      - cd projetcs/app
      - pnpm run build
  - name: docker
    image: plugin/docker
    setting:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      registry: https://home.f1nley.xyz:5000
      repo: homesite-app
