kind: pipeline
type: docker
name: homesite

steps:
  - name: base-build
    image: node:20-slim
    commands:
      - corepack enable
      - corepack use pnpm
      - pnpm i
      - cd projects/app
      - pnpm run build
