kind: pipeline
type: docker
name: homesite

steps:
  - name: build
    image: node:20-slim
    commands:
      - npm config set registry http://mirrors.cloud.tencent.com/npm/
      - corepack enable
      - corepack use pnpm
      - pnpm i
      - cd projects/app
      - pnpm run build
