kind: pipeline
type: docker
name: homesite

steps:
  - name: base-build
    image: node:20-slim
    commands:
      - pwd
      - npm config set registry http://mirrors.cloud.tencent.com/npm/
      - corepack enable
      - corepack use pnpm
      - pnpm i
  - name: app
    image: node:20-slim
    detach: true
    commands:
      - cd projects/app
      - pnpm run build
      - node projects/app/.output/server/index.mjs
  - name: server
    image: node:20-slim
    detach: true
    commands:
      - cd projects/server
      - pnpm run build
      - pnpm run start
