name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      UPLOAD_PATH: "/var/opt/uploads/"
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        with: 
          path: src
      - name: Install pnpm 
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Build
        run: |
          cd ./src/projects/app
          pnpm i
          cd ../..
          pnpm run build
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "./src/projects/app/.output"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_BEFORE: |
            echo 'BEFORE RSYNC'
          SCRIPT_AFTER: |
            echo 'AFTER RSYNC'
            sudo systemctl restart homesite.service
