services:
  pg:
    image: postgres
    restart: unless-stopped
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - homesite:/var/lib/postgresql/data
    networks:
      - homesite
    ports:
      - "15432:5432"

volumes:
  homesite:
networks:
  homesite:
