services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - homesite:/var/lib/postgresql/data

volumes:
  homesite:
