services:
  pg:
    image: postgres:latest
    restart: unless-stopped
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data
    networks:
      - homesite
    ports:
      - "5432:5432"
  # homesite:
  #   image: localhost/homesite:latest
  #   restart: unless-stopped
  #   environment:
  #     JWT_SECRET: "JWT_SECRET"
  #     DATABASE_URL: "postgres://root:rootE@pg:5432/homesite"
  #     UPLOAD_PATH: "/var/opt/uploads"
  #   volumes:
  #     - ./uploads:/var/opt/uploads
  #   networks:
  #     - homesite
  #   ports:
  #     - "3000:3000"
networks:
  homesite:
