services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - homesite:/var/lib/postgresql/data
    networks:
      - homesite
  app:
    image: homesite-app
    networks:
      - homesite

volumes:
  homesite:
networks:
  homesite:
